---
title: "Schedule"
description: |
  Below is a tentative schedule for the event. All times are in EDT.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**9:05: Welcome**


## Block 1: Applied Statistics</span>

-------------------------------------------------------------
 Time             Title                                      Speaker
-------           ----------------------------------         -----------------
9:10 to 9:50      Invited talk: A Bayesian Hierarchical 
                  Time Series Model for Reconstructing       Niamh Cahill
                  Hydroclimate from Multiple Proxies
                  [(abstract)](abstracts.html#niamh-cahill)

9:50 to 10:00     Q & A with Niamh                           Niamh Cahill

10:00 to 10:15    Effect of the infield shift: Causal
                  inference in baseball                      Sonia Markes
                  [(abstract)](abstracts.html#sonia-markes)

10:15 to 10:30     Title TBA                                 Michael Chong

10:30 to 10:40     Q & A with Sonia and Michael              Sonia Markes and Michael Chong

-------------------------------------------------------------


**20 minute break** 

## Block 2: Math Finance and Actuarial Science

-------------------------------------------------------------
 Time             Title                                       Speaker
-------           ----------------------------------          -----------------
11:00 to 11:40    Invited talk: Multiscale modeling 
                  for option pricing and optimal execution     Yuri Saporito
                  [(abstract)](abstracts.html#yuri-saporito) 

11:40 to 11:50    Q & A with Yuri                              Yuri Saporito

11:50 to 12:05    Modelling Heterogeneous Risks with Random 
                  Effects in the Mixture-of-Experts Model      Spark Tseung
                  [(abstract)](abstracts.html#spark-tseung)     

12:05 to 12:20    A Mean Field Game of Sequential Testing      Steven Campbell
                  [(abstract)](abstracts.html#steven-campbell)

12:20 to 12:30    Q & A with Spark and Steven                  Spark Tseung and Steven Campbell

-------------------------------------------------------------


**LUNCH: 75 minutes**

## Block 3: Theoretical Statistics

-------------------------------------------------------------
 Time             Title                                        Speaker
-------           ----------------------------------           -----------------
1:45 to 2:25      Invited talk: Benign Overfitting without
                  Linearity                                    Spencer Frei
                  [(abstract)](abstracts.html#spencer-frei)

2:25 to 2:35       Q & A with Spencer                          Spencer Frei

2:35 to 2:50      Fighting Noise with Noise: Causal 
                  Inference with Many Candidate Instruments    Cindy Zhang
                  [(abstract)](abstracts.html#cindy-zhang)

2:50 to 3:05      Modified Likelihood Root in High
                  Dimensions                                   Yanbo Tang
                  [(abstract)](abstracts.html#yanbo-tang)                               

3:05 to 3:15      Q & A with Cindy and Yanbo                   Cindy Zhang and Yanbo Tang

3:15 to 3:25      **Break**                                              

3:25 to 3:40      Convergence rate bounds for iterative 
                  random functions using one-shot coupling     Sabrina Sixta
                  [(abstract)](abstracts.html#sabrina-sixta)

3:40 to 3:55      Analysis of Langevin Monte Carlo from 
                  Poincaré to Log-Sobolev                      Mufan Li
                  [(abstract)](abstracts.html#mufan-li)

3:55 to 4:05      Q & A with Sabrina and Mufan                 Sabrina Sixta and Mufan Li

4:05 to 4:20      Adaptively Exploiting d-Separators with 
                  Causal Bandits                               Blair Bilodeau
                  [(abstract)](abstracts.html#blair-bilodeau)       

4:20 to 4:35      The Promises of Parallel Outcomes            Ying Zhou
                  [(abstract)](abstracts.html#ying-zhou)

4:35 to 4:45      Q & A with Blair and Ying                    Blair Bilodeau and Ying Zhou

-------------------------------------------------------------
